/** Declaration file generated by dts-gen */

export function getDictionary(
  fileName: any,
  folderPath: any,
  ...args: any[]
): void;

export function getDictionarySync(fileName: any, folderPath: any): any;

export function normalizeDictionary(
  inputPath: any,
  outputPath: any,
  ...args: any[]
): void;
