name: GPT-3 Suggestions
on: [pull_request]

jobs:
  gpt3-suggestions:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_EVENT_PATH: ${{ secrets.$GITHUB_EVENT_PATH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run script
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/openapi-code-suggestions.sh $API_KEY $GITHUB_TOKEN $$GITHUB_EVENT_PATH

      - name: Add suggestions as a comment on the pull request
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: suggestions.txt
