name: On Merge Main
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

  heroku-container-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - build-and-test
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker image
        run: |
          docker build -t spelling-checker:latest .
      - name: Log in to Heroku
        run: heroku container:login --api-key ${{ secrets.HEROKU_API_KEY }}
      - name: Deploy to Heroku
        run: heroku container:release web -a spelling-checker -t latest

  release:
    runs-on: ubuntu-latest
    needs:
      - heroku-container-push
    steps:
      - name: Release to Heroku
        run: echo ${{ secrets.HEROKU_API_KEY }} | heroku container:login
      - name: Release to Heroku
        run: heroku container:release web -a spelling-checker -t latest
