name: On Merge Main
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

  heroku-container-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - build-and-test
    env:
      API_KEY: ${{ secrets.API_KEY }}
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the image
        run: docker build --build-arg API_KEY=*** -t spelling-checker:latest .
      - name: Log in to Heroku
        run: heroku container:login
      - name: Push to Heroku
        run: heroku container:push web -a spelling-checker
      - name: Deploy to Heroku
        run: heroku container:release web -a spelling-checker

