name: On Merge Main
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

  heroku-docker-push-release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - build-and-test
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "spelling-checker"
          heroku_email: "dj_lima@live.com"
          usedocker: true
        env:
          API_KEY: ${{ secrets.API_KEY }}


