name: On Merge Main
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

  heroku-container-push:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker image
        run: |
          docker build -t spelling-checker:latest .
          docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
          docker push registry.heroku.com/spelling-checker:latest/web

  release:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        run: npx semantic-release
