name: On Merge Main
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

  heroku-container-push:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create tag
        run: |
          TAG=$(echo ${GITHUB_SHA} | cut -c1-7)
          git tag $TAG
          git push --tags
      - name: Build and push Docker image
        run: |
          docker build -t registry.heroku.com/spelling-checker/web:$TAG .
          docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
          docker push registry.heroku.com/spelling-checker/web:$TAG